#!/bin/sh
#
# mkttflinks:
# create symbolic links to Truetype Fonts located in C:\WINDOWS\FONTS
#
# Parameter1: mountpoint for DOS drive c:

if test $# -ne 1; then
  echo "$0 <drive_c_mnt_point>"
  exit;
fi


DRIVE_C=$1

test -d /usr/X11R6/lib/X11/fonts/truetype && (
  cd /usr/X11R6/lib/X11/fonts/truetype
  test -d $DRIVE_C/windows/fonts && (
    echo "Creating symbolic links ..."
    for i in $DRIVE_C/windows/fonts/*.ttf
    do
      ln -sfv $i
    done
  )
)
